### ISSUE TITLE
Add linting

### ISSUE THREAD

**Issue by silveltman** [fulldotdev/ui#18]
Add linting as documented here: [https://docs.astro.build/en/editor-setup/](https://docs.astro.build/en/editor-setup/)

For now using eslint and stylelint, as Biome does not have the support yet.

Husky pre-commit

**Comment by jeremybosma** [comment]
https://arc.net/l/quote/lmfuochl

**Comment by jeremybosma** [comment]
Issues like these are now migrated from Github to Linear for internal use.

**Comment by silveltman** [comment]
Closing because we manage the issues we come up with for now internally via Linear
