### ISSUE TITLE
[feat]: Toggle component

### ISSUE THREAD

**Issue by saran13raj** [fulldotdev/ui#43]
### Feature description

A Toggle component similar to https://ui.shadcn.com/docs/components/toggle

### Affected component/components/documentation

Toggle

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by saran13raj** [comment]
I've built the component. You can assign this to me

**Comment by silveltman** [comment]
Thank you @saran13raj , looks good!

As for the PR, I believe you can do the following:

1. Fork the Repo: Click the "Fork" button on the main repository page to create a personal copy.
2. Clone Your Fork: Clone your forked repo to your local machine with:
3. Create a Branch: Create a new branch for your changes:
4. Make Changes: Commit your changes locally.
5. Push to Fork: Push your branch to your fork:
6. Open a Pull Request: Go to the original repository and click "Compare & Pull Request" to submit your changes for review.

We can review the PR, without having to add every contributor als a collaborator on the team.

If I'm missing something and there is a better way, please let me know! If not and you need any more help, just ask! 😁

**Comment by saran13raj** [comment]
@silveltman thanks. I'm with you of creating a PR from forked repo which helps in not add everyone as a contributor.
PR #45 handles this ticket.

**Comment by saran13raj** [comment]
@silveltman do you have a `dev` branch or any similar purposed branch that handles the PRs before prod release?

**Comment by silveltman** [comment]
@saran13raj I have created a `preview` branche in the mean time. This branche will handle PR's before prod release. 

Please check the PR for feedback on your code

**Comment by silveltman** [comment]
I've decided to remove the preview branche for now. Once we will need it, we can add it. For now it is extra work for not real benefit, since we don't have many PR's yet

**Comment by saran13raj** [comment]
> I've decided to remove the preview branche for now. Once we will need it, we can add it. For now it is extra work for not real benefit, since we don't have many PR's yet

undestood. And thanks for taking care of it
