### ISSUE TITLE
[bug]: Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

### ISSUE THREAD

**Issue by JagritGumber** [fulldotdev/ui#44]
### Describe the bug

So I have been getting this error in my command line as soon as I installed `fulldev-ui`
Error:
```sh [error]
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api
```

I am having this only with the combination of postcss, if I use post css as is, I have no errors, If I use just the ui library I have no errors, I am only getting errors with the combination of using both of them

This is my postcss.config.cjs

```cjs [postcss.config.js]
module.exports = {
  plugin: [
    require("postcss-preset-env")({
      stage: 0,
    }),
  ],
};
```

### Affected component/components/documentation

None

### How to reproduce

1. Setup a basic empty astro project with the recommended settings
2. Use bun as package manager
3. install the following
```sh
bun install postcss postcss-preset-env
```
4. Setup the postcss with this config
```cjs
module.exports = {
  plugin: [
    require("postcss-preset-env")({
      stage: 0,
    }),
  ],
};
```
5. Install fulldev-ui and copy the header component from the building blocks
```astro
---
import Header from 'fulldev-ui/components/Header.astro'
import HtmlWrapper from "../layouts/HtmlWrapper.astro"
---
<HtmlWrapper title="Home" desc="">
	<Header
  heading="Some Blog by Jagrit"
  links={[
		{
			text: 'Docs',
      href: '/overview/introduction/',
    },
    {
			text: 'Github',
      href: 'https://github.com/fulldotdev/ui',
    },
  ]}
  buttons={[
		{
			text: 'Docs',
      href: '/overview/introduction/',
    },
    {
			title: 'X / Twitter',
      icon: 'brand-x',
      href: 'https://x.com/silveltm',
      target: '_blank',
    },
  ]}
  frame="fill"
  position="relative"
	/>
</HtmlWrapper>
```

### Logs

```bash
It's just a warning in the console in my VS Code


Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api

Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api

Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api

Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api

Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by silveltman** [comment]
Thanks for raising the issue @JagritGumber

We got this warning recently when we we updated the dependencies in the project. We don't use any Sass api's ourselves, so this is probably something caused by how Vite works with the new version of sass.

We will look into it, but you don't have to worry about it causing problems in the meantime, just a warning.

**Comment by silveltman** [comment]
I've found [this issue](https://github.com/sass/dart-sass/issues/2352) in the meantime.

We have fixed this by using this setting:
```
  css: {
    preprocessorOptions: {
      scss: {
        api: 'modern',
      },
    },
  }
```

Only thing is that we can only do this in the astro integration. I still want everything to work fine without a need for the integration, so for now I downgraded sass to v1.78.0.

This will remove the warning and also makes the components usable without the astro integration. We plan to add more options etc via the integration, improve the documentation on it, and test/support the `astro add` command. When we do this and using the integration will be easier, we will bump up sass again.

**Comment by varunguptha** [comment]
<w> Deprecation The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
<w>
<w> More info: https://sass-lang.com/d/legacy-js-api
<w>
<w> null


Getting this in my react project and in my project there is no cofig file how can i add it and get rid of this warning

**Comment by JagritGumber** [comment]
@varunguptha If you opened that url and went to the following section it mentions about how to add settings in your vite or react app [Link](https://sass-lang.com/documentation/breaking-changes/legacy-js-api/#:~:text=If%20you%E2%80%99re%20using%20a,Sass%C2%A0API.) If the App was made with create-react-app then follow the webpack guide, else if it was made with vite@latest follow the vite guide
